[package]
name = "bounties"
version = "2.0.1"
authors = ["Oleh Ivaniuk <fedencer7@gmail.com>"]
edition = "2021"

[dependencies]
near-sdk = "4.1.1"
near-contract-standards = "4.1.1"

[lib]
crate-type = ["cdylib", "rlib"]
